version: '3.4'

services:
  proxy:
    image: lewos/reverseproxy_nginx
    build:
        context:  ./nginx
        dockerfile: Dockerfile
    ports:
        - "80:80"
    volumes:
          #<carpeta del host> : <carpeta del contenedor>
          - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ${PWD}:/letsencrypt
          - ${PWD}/certs:/etc/letsencrypt
          